# This is a basic workflow to help you get started with Actions

name: Python package
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "workshop" branch
  push:
    branches: [ "workshop" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 pylint pyflakes pytest pytest-cov

      - name: Run autopep8
        run: |
          autopep8 --in-place --recursive . > HW2/autopep8_trace.txt
          cat HW2/autopep8_trace.txt

      - name: Run pylint
        run: |
          pylint HW2/hw2_debugging.py > HW2/pylint_trace.txt
          cat HW2/pylint_trace.txt

      - name: Run pyflakes
        run: |
          pyflakes HW2/hw2_debugging.py > HW2/pyflakes_trace.txt
          cat HW2/pyflakes_trace.txt    
          
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest HW2/test_cases.py
